allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
  vue-demi: true
<<<<<<< HEAD
onlyBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver
  - vue-demi
  - '*'
=======
>>>>>>> 2dc3a4c6557394b004089da10a6c56467e18b325
