allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
  vue-demi: true
<<<<<<< HEAD
onlyBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver
  - vue-demi
  - '*'
=======
>>>>>>> 9c69ceb712d475b9a9bd31fc9b787240061a05a5
