allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
  vue-demi: true
<<<<<<< HEAD
onlyBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver
  - vue-demi
  - '*'
=======
>>>>>>> 4eaa852d0b2d1f8c70fd2db2aa5d5283d32e00f8
